kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami 
  namespace: default
  labels:
    app: whoami 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami 
  template:
    metadata:
      labels:
        app: whoami 
        type: default
    spec:
      containers:
      - image: containous/whoami 
        name: whoami 
        ports:
        - name: http
          containerPort: 80
