kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world-with-svc 
  namespace: default
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world 
        type: default
    spec:
      containers:
      - image: vad1mo/hello-world-rest
        name: hello-world
        ports:
        - name: http
          containerPort: 5050
