apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: utn
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
