apiVersion: v1
kind: Pod
metadata:
  name: dnsutils-sa
  namespace: default
spec:
  serviceAccountName: demo-service-account
  containers:
  - name: dnsutils-sa
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
