apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  containers:
  - name: whoami
    image: containous/whoami 
    ports:
     - name: http
       containerPort: 80
  - name: dns-utils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
