apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  containers:
  - name: hello-world
    image: vad1mo/hello-world-rest
    ports:
     - name: http
       containerPort: 5050
  - name: dns-utils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
